import { StyleSheet } from 'react-native';
import { Colors, GameColors } from '../../theme';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { padding: 16, paddingBottom: 60 },
  panel: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 20,
    padding: 20,
    borderTopWidth: 3,
    borderTopColor: GameColors.letters,
  },
  plabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: Colors.muted,
    marginBottom: 14,
  },
  sublabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: Colors.muted,
  },
  diffRow: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  diffBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    alignItems: 'center',
  },
  diffTxt: { fontFamily: 'Outfit_600SemiBold', fontSize: 13, color: Colors.ink2 },
  diffSub: { fontFamily: 'Outfit_300Light', fontSize: 10, color: Colors.muted, marginTop: 2 },
  totalsRow: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  totalBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 9,
    backgroundColor: Colors.card,
  },
  totalTxt: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 14, color: Colors.ink2 },
  scoreRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  scoreItem: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
  },
  scoreVal: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 20 },
  scoreLbl: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 9,
    color: Colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 2,
  },
  wordRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    justifyContent: 'center',
    marginBottom: 8,
    minHeight: 56,
  },
  lchar: {
    width: 38,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 2,
  },
  lcharShown: { backgroundColor: Colors.surface, borderColor: Colors.border },
  lcharBlank: { backgroundColor: Colors.card, borderColor: Colors.border, borderStyle: 'dashed' },
  lcharFilled: { borderColor: GameColors.letters, backgroundColor: 'rgba(180,83,9,0.05)' },
  lcharOk: { backgroundColor: Colors.green, borderColor: Colors.greenBorder },
  lcharNo: { backgroundColor: Colors.red, borderColor: Colors.redBorder },
  lcharTxt: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 20, color: Colors.ink },
  wordHint: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 12,
    color: Colors.muted,
    textAlign: 'center',
    marginBottom: 4,
  },
  btnRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  btn: { paddingVertical: 13, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center' },
  btnTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: '#fff' },
  btnS: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    alignItems: 'center',
  },
  btnSTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: Colors.ink },
});
