import { StyleSheet } from 'react-native';
import { Colors, GameColors } from '../../theme';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { padding: 16, paddingBottom: 60 },
  panel: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 20,
    padding: 16,
    borderTopWidth: 3,
    borderTopColor: GameColors.schulte,
    alignItems: 'center',
  },
  plabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: Colors.muted,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  desc: {
    fontFamily: 'Outfit_300Light',
    fontSize: 13,
    color: Colors.ink2,
    marginBottom: 8,
    alignSelf: 'flex-start',
    lineHeight: 20,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    padding: 6,
  },
  stepBtn: {
    width: 30,
    height: 30,
    backgroundColor: Colors.card,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTxt: { fontFamily: 'Outfit_700Bold', fontSize: 18, color: Colors.ink },
  stepVal: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 17,
    color: Colors.ink,
    minWidth: 52,
    textAlign: 'center',
  },
  hint: { fontFamily: 'JetBrainsMono_400Regular', fontSize: 11, color: Colors.muted, marginTop: 6 },
  btn: {
    paddingVertical: 13,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  btnTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: '#fff' },
  stopwatch: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 32,
    color: Colors.ink,
    marginBottom: 4,
  },
  target: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 13,
    color: Colors.muted,
    marginBottom: 14,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  cell: {
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellFlash: {
    backgroundColor: Colors.red,
    borderColor: Colors.redBorder,
  },
  cellTapped: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  cellTxt: {
    fontFamily: 'JetBrainsMono_700Bold',
    color: Colors.ink,
  },
  wrongCount: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    color: Colors.accent,
    marginTop: 10,
    height: 16,
  },
});
