import { StyleSheet } from 'react-native';
import { Colors, GameColors } from '../../theme';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { padding: 16, paddingBottom: 60 },
  panel: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 20,
    padding: 24,
    borderTopWidth: 3,
    borderTopColor: GameColors.words,
  },
  plabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: Colors.muted,
    marginBottom: 16,
  },
  chipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 60 },
  chip: {
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  chipTxt: { fontFamily: 'Outfit_600SemiBold', fontSize: 15, color: Colors.ink },
  chipOrdered: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  chipNum: { fontFamily: 'JetBrainsMono_400Regular', fontSize: 11, color: Colors.muted },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  inputNum: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    color: Colors.muted,
    width: 20,
    textAlign: 'right',
  },
  input: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 13,
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 15,
    color: Colors.ink,
  },
  inputOk: { borderColor: Colors.accent3, backgroundColor: Colors.green, color: Colors.greenText },
  inputNo: { borderColor: Colors.accent, backgroundColor: Colors.red, color: Colors.redText },
  inputIcon: { width: 20, fontSize: 15, textAlign: 'center' },
  btnRow: { flexDirection: 'row', gap: 10, marginTop: 20 },
  btn: { paddingVertical: 13, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center' },
  btnTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: '#fff' },
  btnS: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    alignItems: 'center',
  },
  btnSTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: Colors.ink },
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 4 },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    padding: 6,
  },
  stepBtn: {
    width: 30,
    height: 30,
    backgroundColor: Colors.card,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTxt: { fontFamily: 'Outfit_700Bold', fontSize: 18, color: Colors.ink },
  timeVal: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 17,
    color: Colors.ink,
    minWidth: 44,
    textAlign: 'center',
  },
  attRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  attBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 9,
    backgroundColor: Colors.card,
  },
  attTxt: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 14, color: Colors.ink2 },
  hint: { fontFamily: 'JetBrainsMono_400Regular', fontSize: 11, color: Colors.muted, marginTop: 6 },
  missed: { marginTop: 16 },
  missedT: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 10,
    color: Colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  missedChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  missedChip: {
    backgroundColor: Colors.red,
    borderWidth: 1,
    borderColor: Colors.redBorder,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  missedChipTxt: { fontFamily: 'Outfit_700Bold', fontSize: 13, color: Colors.redText },
  attemptInfo: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    color: Colors.muted,
    textAlign: 'center',
    marginTop: 10,
  },
  noisePatch: {
    position: 'absolute',
    width: 60,
    height: 28,
    borderRadius: 8,
    opacity: 0.18,
  },
  distractRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  distractLabel: {
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 14,
    color: Colors.ink,
    flex: 1,
  },
});
