import { StyleSheet } from 'react-native';
import { Colors, GameColors } from '../../theme';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  scroll: { padding: 16, paddingBottom: 60 },
  panel: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 20,
    padding: 24,
    borderTopWidth: 3,
    borderTopColor: GameColors.seq,
  },
  plabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: Colors.muted,
    marginBottom: 16,
  },
  sublabel: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: Colors.muted,
  },
  lenRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    padding: 6,
  },
  stepBtn: {
    width: 30,
    height: 30,
    backgroundColor: Colors.card,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTxt: { fontFamily: 'Outfit_700Bold', fontSize: 18, color: Colors.ink },
  stepVal: {
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 17,
    color: Colors.ink,
    minWidth: 44,
    textAlign: 'center',
  },
  presets: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  preset: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 8,
    backgroundColor: Colors.card,
  },
  presetTxt: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 12, color: Colors.ink2 },
  hint: { fontFamily: 'JetBrainsMono_400Regular', fontSize: 11, color: Colors.muted, marginTop: 6 },
  switchRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 16, marginBottom: 4 },
  switchLabel: { fontFamily: 'Outfit_400Regular', fontSize: 14, color: Colors.ink2, flex: 1 },
  seqRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    minHeight: 60,
    alignItems: 'center',
  },
  seqNum: {
    width: 50,
    height: 50,
    backgroundColor: Colors.surface,
    borderWidth: 2,
    borderColor: Colors.border,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seqNumTxt: { fontFamily: 'JetBrainsMono_700Bold', fontSize: 22, color: Colors.ink },
  bigInput: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderWidth: 2,
    borderColor: Colors.border,
    borderRadius: 13,
    paddingVertical: 14,
    fontFamily: 'JetBrainsMono_700Bold',
    fontSize: 24,
    color: Colors.ink,
    textAlign: 'center',
    letterSpacing: 4,
  },
  seqHint: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 12,
    color: Colors.muted,
    textAlign: 'center',
    marginTop: 8,
  },
  btnRow: { flexDirection: 'row', gap: 10, marginTop: 20 },
  btn: { paddingVertical: 13, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center' },
  btnTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: '#fff' },
  btnS: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    alignItems: 'center',
  },
  btnSTxt: { fontFamily: 'Outfit_700Bold', fontSize: 15, color: Colors.ink },
  seqCompare: { marginTop: 14, marginBottom: 4 },
  seqCompareTxt: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 13,
    color: Colors.muted,
    lineHeight: 24,
  },
});
